GET http://localhost:3333/prompts

### 
GET http://localhost:3333/questions

### 
POST http://localhost:3333/question
Content-Type: application/json

{
    "reciverId": "clnlpooa20000ix74skqamv64",
    "question": "testeeee",
    "transmitter": "Gabriel Gomes Vieira"
}
