GET http://localhost:3333/prompts

### 
GET http://localhost:3333/questions

### 
GET http://localhost:3333/recivers

### 
POST http://localhost:3333/view/clnm01cbl0001ixk4xqza5m5a/true
{
    viewed: true
}

### 
POST http://localhost:3333/question
Content-Type: application/json

{
    "reciverId": "clnlpooa20000ix74skqamv64",
    "question": "testeeee",
    "transmitter": "Gabriel Gomes Vieira"
}
